import numpy as np
from mujoco import _structs, gl_context as gl_context
from typing import Optional, Union

class Renderer:
    def __init__(self, model: _structs.MjModel, height: int = ..., width: int = ..., max_geom: int = ...) -> None: ...
    @property
    def model(self): ...
    @property
    def scene(self) -> _structs.MjvScene: ...
    @property
    def height(self): ...
    @property
    def width(self): ...
    def enable_depth_rendering(self) -> None: ...
    def disable_depth_rendering(self) -> None: ...
    def enable_segmentation_rendering(self) -> None: ...
    def disable_segmentation_rendering(self) -> None: ...
    def render(self) -> np.ndarray: ...
    def update_scene(self, data: _structs.MjData, camera: Union[int, str, _structs.MjvCamera] = ..., scene_option: Optional[_structs.MjvOption] = ...): ...
