from _typeshed import Incomplete
from absl.testing import parameterized
from mujoco import rollout as rollout

TEST_XML: str
TEST_XML_NO_SENSORS: str
TEST_XML_NO_ACTUATORS: str
TEST_XML_MOCAP: str
TEST_XML_EMPTY: str
ALL_MODELS: Incomplete

class MuJoCoRolloutTest(parameterized.TestCase):
    def setUp(self) -> None: ...
    def test_single_step(self, model_name) -> None: ...
    def test_single_rollout(self, model_name) -> None: ...
    def test_multi_step(self, model_name) -> None: ...
    def test_single_rollout_fixed_ctrl(self, model_name) -> None: ...
    def test_multi_rollout(self, model_name) -> None: ...
    def test_multi_rollout_fixed_ctrl_infer_from_output(self, model_name) -> None: ...
    def test_multi_rollout_multiple_inputs(self, arg_nstep, model_name) -> None: ...
    def test_threading(self) -> None: ...
    def test_time(self) -> None: ...
    def test_warmstart(self) -> None: ...
    def test_mocap(self) -> None: ...
    def test_intercept_mj_errors(self) -> None: ...
    def test_invalid(self) -> None: ...
    def test_bad_sizes(self) -> None: ...
    def test_stateless(self) -> None: ...

def get_state(data): ...
def set_state(model, data, state) -> None: ...
def step(model, data, state, **kwargs): ...
def single_rollout(model, data, initial_state, **kwargs): ...
def multi_rollout(model, data, initial_state, **kwargs): ...
